FROM node AS frontend

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node

WORKDIR /app

COPY --from=frontend /app/dist ./dist

RUN npm install -g serve

EXPOSE 5000

# Start the web server
CMD ["serve", "-s", "dist", "-p", "5000"]